spring:
  application:
    name: user-server
  datasource:
    url: jdbc:mysql://localhost:3306/oj?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
  cloud:
    nacos:
      server-addr: localhost:8848
  mail:
    protocol: smtp
    host: smtp.qq.com
    port: 587
    username: $$$QQ邮箱$$$
    password: $$$STMP秘钥$$$
    test-connection: false
    default-encoding: UTF-8
  data:
    redis:
      host: 106.52.199.168
      port: 6379
      # 链接超时时间
      timeout: 10s
      lettuce:
        pool:
          # 连接池最大连接数
          max-active: 100
          # 连接池最大阻塞等待时间
          max-wait: 100ms
          # 连接池中最大空闲链接数
          max-idle: 3
          # 连接池中最小空闲链接数
          min-idle: 0
server:
  port: 8778

springdoc:
  swagger-ui:
    path: /swagger
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /user/api-docs

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

sa-token:
  # token名称 (同时也是cookie名称)
  token-name: authorization
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  active-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: true
  #  读取请求头中的token
  isReadHeader: true
  #  取消cookie
  isReadCookie: false

aliyun:
  oss:
    file:
      endpoint: $$$ OSS阿里云地区节点 $$$
      keyid: $$$ OSS阿里云账户 $$$
      keysecret: $$$ OSS阿里云秘钥 $$$
      bucketname: $$$ OSS阿里云桶名 $$$
      foldername: $$$ OSS阿里云文件夹名 $$$